extends Node

enum { HARDY, LONELY, ADAMANT, NAUGHTY, BRAVE, 
	   BOLD, DOCILE, IMPISH, LAX, RELAXED, 
	   MODEST, MILD, BASHFUL, RASH, QUIET, 
	   CALM, GENTLE, CAREFUL, QUIRKY, SASSY, 
	   TIMID, HASTY, JOLLY, NAIVE, SERIOUS }
